question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "History",
        "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "Bugatti was an Italian car manufacturer.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Kissing someone for one minute burns about 2 calories.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "New Haven is the capital city of the state of Connecticut in the United States.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "Water is naturally coloured blue.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Mythology",
     "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The Battle of Trafalgar took place on October 23rd, 1805",
     "correct_answer": "False", "incorrect_answers": ["True"]
     }
]
